### PR TITLE
feat: can use specific s3 bucket to deploy the alexa backend by using cfn-deployer

### PR DESCRIPTION
**Pull request by hideokamoto**
## Expect

Using AWS CloudFormation, we want to use own specific S3 bucket to deploy our stack.

### Example - Serverless Framework
https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

```
provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: com.serverless.${self:provider.region}.deploys # Deployment bucket name. Default is generated by the framework
```

## Actual

We can not use a specific s3 bucket.
The CLI use only already created bucket or create a new one.

## Description of changes:

On `ask-resources.json`, we want to set own specific S3 bucket name.

```json
{
  "askcliResourcesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillMetadata": {
        "src": "./skill-package"
      },
      "code": {
        "default": {
          "src": "./lambda"
        }
      },
      "skillInfrastructure": {
        "userConfig": {
          "runtime": "nodejs10.x",
          "handler": "index.handler",
          "templatePath": "./infrastructure/cfn-deployer/skill-stack.yaml",
          "awsRegion": "us-east-1",
          "deploymentBucket": "example-bucket-name"
        },
        "type": "@ask-cli/cfn-deployer"
      }
    }
  }
}
```

The Pull Request is the patch for the feature and try to add a simple unit test for the function.

Best Regards.

### CODE REVIEW

**Comment by hideokamoto** [comment]
Any updates?
If you have any questions or issues, please tell me.

Thanks.

**Comment by RonWang** [comment]
Hey @hideokamoto ,

Sorry for the late response! We were having a discussion over your very reasonable feature request. In fact, we have thought about the similar feature when we implement the cfn-deployer, especially with the support to let users configure the s3 uploader for each region. 

However, because the Lambda function is very regional and we involve some s3 configuration, the codebase provisioning is defined as a blackbox to avoid confusion:
* First, for cross-region Cloudformation, s3 bucket has to be created at the region you deploy the stack. This becomes the main reason that influenced our decision. We decided to take over the codebase provisioning with s3 replication. Our blackbox makes sure that users can focus on the stack resources for their cross-region deployment.
* Second, as you may know we enable the s3 bucket object version as our driver to detect if a code change happens, and further updates the stack. However, we cannot detect when the bucket is not initiated from us. 
* Last but not least, this s3 bucket is like a skill static content ask-cli owns full control with, which also gives ask-cli the extensibility to store some other type of skill artifacts when we need. 

With those said, we still really thank you for the contribution and think from your angle:
* If you need to reuse a s3 bucket, one quick hack would be to modify the s3.bucket and s3.key in the .ask/ask-states.json, and delete the objectVersion field to force CLI upload your local code to the target s3. Or you might need to download the code base, and use `ask init` to form the ask-resources.json to control your deploy.
* Another root solution and you might be interesting is: since Serverless as a well-known framework solves this issue, even including cross-region, would you be interested to develop a @hideokamoto/serverless-deployer :)? We do have the inclination to make this skill backend as a platform and let developers build their own deployers. Thus, we leave a lot of spaces for this [deployer class](https://github.com/alexa/ask-cli/blob/develop/lib/controllers/skill-infrastructure-controller/deploy-delegate.js#L32-L55). Let me know if you are interested in contributing, we can help you answer any question all the way through!

Thanks,
Ron

**Comment by hideokamoto** [comment]
@RonWang 

Thanks for a kindful answer!

> If you need to reuse a s3 bucket, one quick hack would be to modify the s3.bucket and s3.key in the .ask/ask-states.json, and delete the objectVersion field to force CLI upload your local code to the target s3. Or you might need to download the code base, and use ask init to form the ask-resources.json to control your deploy.

Is it possible to use this way for the initial deployment?
I think the `.ask/ask-states.json` file and `s3` properties are made at after initial deployment.
In our AWS account, sometimes we get the S3 bucket number limitation error. 
So if the CLI creates an unuse S3 bucket, we have to delete bucket by ourselves.
That's why we want to use existed S3 bucket.

> would you be interested to develop a @hideokamoto/serverless-deployer :)?

Do you mean to add a new deployer for Serverless Framework as a community library?
I think it's really interesting, because, before ASK CLI(v2), we're using it to deploy our Skill's function to AWS.
How can we create a deployer ?

**Comment by hideokamoto** [comment]
I think we need to discuss it.
So I've created a issue about it.
https://github.com/alexa/ask-cli/issues/174

**Comment by hideokamoto** [comment]
Our goal is `Deploy multiple Lambda code to single S3 bucket`.
Even if this PR is not a good solution about it, we can find out another good way by discussing the issue :)

**Comment by kakhaUrigashvili** [comment]
@hideokamoto Closing in favor of https://github.com/alexa/ask-cli/pull/317. Please provide feedback on https://github.com/alexa/ask-cli/pull/317

**Pull request closed without merging**
