### PR TITLE
fix: maven-assembly-plugin 2.6 doesn't work with Java > 8

### LINKED ISSUE #372: The plugin used to deploy Maven project doesn't support Java > 8.
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

I'm trying to deploy a skill, based on a Java codebase.
Deployment fails because of the usage of an old version of the [maven-assembly-plugin](http://maven.apache.org/plugins/maven-assembly-plugin/index.html) which I believe doesn't work well using Java >8.

As far as I can tell, version [2.6](https://github.com/apache/maven-assembly-plugin/releases/tag/maven-assembly-plugin-2.6) is hardocded [here](https://github.com/alexa/ask-cli/blob/v2.22.2/lib/builtins/build-flows/java-mvn.js#L37).

## Expected Behavior

When working with the `lambda-deployer` and entering the `ask deploy` command in a Java environment with a Maven project,
A new fat jar with the descriptor `jar-with-dependencies` is supposed to be created with the  [maven-assembly-plugin](http://maven.apache.org/plugins/maven-assembly-plugin/index.html) and deployed.

## Current Behavior

The  [maven-assembly-plugin](http://maven.apache.org/plugins/maven-assembly-plugin/index.html) fails to create the fat jar, and throws the following error:

```text
[WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver
java.lang.ExceptionInInitializerError
```

**CLI Snapshot**

## Steps to Reproduce (for bugs)

Any maven Java project, using Java > 8 should fail when deployed.

## Possible Solution

I will push a PR soon trying to bump this **2015** [2.6](https://github.com/apache/maven-assembly-plugin/releases/tag/maven-assembly-plugin-2.6)  version to the latest **2020** [3.3.0](https://github.com/apache/maven-assembly-plugin/releases/tag/maven-assembly-plugin-3.3.0) version.

## Your Environment and Context

* ask-cli version: 2.22.2
* Operating System and version: Windows 10
* Node.js version used for development: 15.4.0
* NPM version used for development: 7.0.15

### PR DESCRIPTION
**Pull request by TomerFi**
… failures

*Issue #, if available:*
 fixes #372

*Description of changes:*

Bumping the **2015** [2.6](https://github.com/apache/maven-assembly-plugin/releases/tag/maven-assembly-plugin-2.6) `maven-assembly-plugin`  version to the latest **2020** [3.3.0](https://github.com/apache/maven-assembly-plugin/releases/tag/maven-assembly-plugin-3.3.0) one.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kakhaUrigashvili** [comment]
@TomerFi thank you for contributing. Looks like the update does not work for Java 8

I think there are 2 options to handle this:
1) find version of maven-assembly-plugin that work for both Java 8 and 9<= (not sure if it exists).
2) Add condition into JavaMvnBuildFlow to use different version of maven-assembly-plugin based on Java version.

You can run 'npm run integration-test' to test Java build flow without need to deploy a skill.

https://github.com/alexa/ask-cli/blob/develop/test/integration/code-builder/code-builder-test.js#L70

**Comment by TomerFi** [comment]
@kakhaUrigashvili 

That's weird,
It doesn't work.

I even reverted my modification,
The integration test fails regardless.

It's late, maybe I'm missing something, maybe it's something in my environment.
I'll look into it again tomorrow.

Thanks!
:-)

**Comment by TomerFi** [comment]
@kakhaUrigashvili 
Yes, turns out the maven assembly plugin broke support for Java 8 with version 3.
And vice-versa, version 2 doesn't support Java > 8.

So we need to verify the java version in [java-mvn.js](https://github.com/alexa/ask-cli/blob/v2.22.2/lib/builtins/build-flows/java-mvn.js#L37) and for java >8 use the 3.3.0, else use 2.6.
And of course, adjust the unit tests accordingly.

So this PR is a little bit bigger then what I intended to,
It might take me a couple of days to get through this,
as I don't do js on a day to day basis.

Should this PR be closed and reopened or perhaps marked as wip?

**Comment by kakhaUrigashvili** [comment]
@TomerFi thank you. I marked this PR as in draft. We can keep it open.

**Comment by TomerFi** [comment]
@kakhaUrigashvili 

So, after playing around with this thing.
I've managed to get the java version using [find-java-home](https://www.npmjs.com/package/find-java-home) and modify the execution command accordingly.

And then it hit me, I must have been too tired last night, so I missed it.
The problem isn't the java running, it's maven's assembly plugin configuration.

The `2.6` version doesn't work with java > 8, that's a given.

With `2.6` to construct a fat jar, we can use the [assembly goal](https://maven.apache.org/plugins-archives/maven-assembly-plugin-2.6/assembly-mojo.html).
Which takes (although deprecated at the time) a [descriptorId](https://maven.apache.org/plugins-archives/maven-assembly-plugin-2.6/assembly-mojo.html#descriptorId) parameter.

This can easily be configured via the command line, that's what's being done today [here](https://github.com/alexa/ask-cli/blob/v2.22.2/lib/builtins/build-flows/java-mvn.js#L37):

```javascript
this.execCommand('mvn clean org.apache.maven.plugins:maven-assembly-plugin:2.6:assembly '
        + '-DdescriptorId=jar-with-dependencies package');
```

Version [3.3.0] doesn't break Java support, it does work with Java < 9.

But the configuration has changed.
The `assembly goal` was removed, as was the deprecated `descriptorId` parameter.

Instead, we can use the [single goal](http://maven.apache.org/plugins/maven-assembly-plugin/single-mojo.html) to create the fat jar.

The `single goal` takes a list of [descriptorRefs](http://maven.apache.org/plugins/maven-assembly-plugin/single-mojo.html#descriptorRefs).
To illustrate, the new command line execution line, should be something of the sorts:

```javascript
this.execCommand('mvn clean org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single '
        + '-DdescriptorRefs=[jar-with-dependencies] package');
```

That of course doesn't work, maven doesn't seem to accept list values from the command line.

The appropriate and easiest solution,
Would be to instruct the users via the documentation to describe the assembly plugin in their plugin management section in their own pom file, like so:

(I've tested this with the [integration test java project](https://github.com/alexa/ask-cli/blob/v2.22.2/test/integration/fixtures/code-builder/java-mvn/lambda/pom.xml) and it works well.)

```xml
<plugin>
  <artifactId>maven-assembly-plugin</artifactId>
  <version>3.3.0</version>
  <configuration>
    <descriptorRefs>
      <descriptorRef>jar-with-dependencies</descriptorRef>
    </descriptorRefs>
  </configuration>
</plugin>
```

Then we can modify the execution command as follows:

```javascript
this.execCommand('mvn clean org.apache.maven.plugins:maven-assembly-plugin:single package');
```

And it should work for everyone regardless of the java version used.

Note that this actually letting the users set the version and the descriptor ref, by themselves.

I'm still playing around with this,
Maybe I'll figure out a way to set the descriptor ref from the command line.

**Comment by TomerFi** [comment]
@kakhaUrigashvili 

If this gets approved,
I'll be happy to update the documentation as well prior to the merge process.
If you could only point to the documentation sources (if they are open to public contributions).

**Comment by kakhaUrigashvili** [comment]
@TomerFi I see that integration test passes now, but when I run manually ask deploy with Java 11, it fails.

I think we will need to update templates for Java to support your fix.

https://ask-cli-static-content.s3-us-west-2.amazonaws.com/skill-templates/java-templates.json

I will need to talk to the team about it.

**Comment by TomerFi** [comment]
@kakhaUrigashvili 
I can take care of the templates,
I'll push some PR's and reference this one,
So they can be merged simultaneously if this change will get approved.

But I am concern about the build failure you've encountered.

I'm currently working on refactoring a skill I maintained.
It's still a WIP so there's not much to see yet.

But I have been using the modified version of ask cli [here](https://github.com/TomerFi/alexa-skill-shabbat-times/blob/better-project/package.json#L34) within a java 11 environment,
and I've successfully deployed the project on multiple occasions.

Maybe there's a maven version incompatibility involved here,
I think Github runners come with a built-in java 8 + java 11 but uses java 8 as default.
Maybe it's worth updating the ci workflows as well to test both versions.

**Comment by kakhaUrigashvili** [comment]
@TomerFi I tested (deploy and dialog commands) Java 11 before your code change and it worked for me. Here Java 11 version, I am using:
```
java -version
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)
```

**Comment by TomerFi** [comment]
@kakhaUrigashvili 
Can you check your maven version?

```shell
mvn --version
```

And please, if you got an error or any other information to share.

I'm running maven 3.6.3 and it seems to work well.

**Comment by kakhaUrigashvili** [comment]
> ```shell
> mvn --version
> ```

@TomerFi my maven version is 
```
mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
```

**Comment by TomerFi** [comment]
@kakhaUrigashvili 
Can you please check what version of `maven-compiler-plugin` is configured in your `pom.xml`.
I read somewhere that `Java 11` requires `3.8.0`, the latest is `3.8.1`.
In the integration test, it's configured to [3.7.0](https://github.com/alexa/ask-cli/blob/v2.22.2/test/integration/fixtures/code-builder/java-mvn/lambda/pom.xml#L45).

**Comment by kakhaUrigashvili** [comment]
> @kakhaUrigashvili
> Can you please check what version of `maven-compiler-plugin` is configured in your `pom.xml`.
> I read somewhere that `Java 11` requires `3.8.0`, the latest is `3.8.1`.
> In the integration test, it's configured to [3.7.0](https://github.com/alexa/ask-cli/blob/v2.22.2/test/integration/fixtures/code-builder/java-mvn/lambda/pom.xml#L45).

I am using 3.7.0 used in this template https://github.com/RonWang/skill-sample-java-premium-hello-world/blob/master/pom.xml#L31

```
cat lambda/pom.xml 
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
.............

  <build>
    <sourceDirectory>src</sourceDirectory>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
            <forceJavacCompilerUse>true</forceJavacCompilerUse>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  
</project>
a483e7e143b4:alexa-sample-java kakuri$ java --version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)
a483e7e143b4:alexa-sample-java kakuri$ ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

==================== Deploy Skill Metadata ====================
[Warn]: The hash of current skill package folder does not change compared to the last deploy hash result, CLI will skip the deploy of skill package.
Skill ID: amzn1.ask.skill.6aa388a2-64ad-4820-bf6e-83d5163b61b5

==================== Build Skill Code ====================
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< alexa-skills-kit-samples:helloworld >-----------------
[INFO] Building helloworld 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ helloworld ---
[INFO] 
[INFO] ----------------< alexa-skills-kit-samples:helloworld >-----------------
[INFO] Building helloworld 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> maven-assembly-plugin:2.6:assembly (default-cli) > package @ helloworld >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ helloworld ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/kakuri/test/alexa-sample-java/.ask/lambda/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ helloworld ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 7 source files to /Users/kakuri/test/alexa-sample-java/.ask/lambda/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ helloworld ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/kakuri/test/alexa-sample-java/.ask/lambda/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ helloworld ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ helloworld ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ helloworld ---
[INFO] Building jar: /Users/kakuri/test/alexa-sample-java/.ask/lambda/target/helloworld-1.0.jar
[INFO] 
[INFO] <<< maven-assembly-plugin:2.6:assembly (default-cli) < package @ helloworld <<<
[INFO] 
[INFO] 
[INFO] --- maven-assembly-plugin:2.6:assembly (default-cli) @ helloworld ---
[INFO] Building jar: /Users/kakuri/test/alexa-sample-java/.ask/lambda/target/helloworld-1.0-jar-with-dependencies.jar
[INFO] 
[INFO] ----------------< alexa-skills-kit-samples:helloworld >-----------------
[INFO] Building helloworld 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ helloworld ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/kakuri/test/alexa-sample-java/.ask/lambda/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ helloworld ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ helloworld ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/kakuri/test/alexa-sample-java/.ask/lambda/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ helloworld ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ helloworld ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ helloworld ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.663 s
[INFO] Finished at: 2021-01-25T09:54:49-08:00
[INFO] ------------------------------------------------------------------------
Skill code built successfully.
Code for region default built to /Users/kakuri/test/alexa-sample-java/.ask/lambda/build.zip successfully with build flow JavaMvnBuildFlow.
...........
```

I installed Java 11 using https://sdkman.io/

**Comment by TomerFi** [comment]
I'm sorry for the delayed response.
I'm stuck on another project.
I'll get around to reexamine this in a couple of days.

Thank you.

**Comment by TomerFi** [comment]
@kakhaUrigashvili
I've pushed a PR with a similar modifications to @RonWang fork https://github.com/RonWang/skill-sample-java-premium-hello-world/pull/1

Can you please have a look?
I will push similar PRs to the original and other templates repository if this gets approved.

**Comment by TomerFi** [comment]
@kakhaUrigashvili @RonWang 
Ping... :smirk:

**Comment by TomerFi** [comment]
@kakhaUrigashvili @RonWang 
If there's anything I can do to move this PR forward,
Please let me know.

Thanks.

**Pull request closed without merging**
